from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, EmailStr

notes="""
[ Raw JSON Client Input ]
       │
       ▼
 ┌───────────┐
 │   INPUT   │ Validate data shapes, lengths, types (e.g., string vs integer)
 └─────┬─────┘
       │  If Valid
       ▼
 ┌───────────┐
 │  BACKEND  │ Process logic, auto-generate attributes (e.g., id=10, date="Jul 2026")
 └─────┬─────┘
       │
       ▼
 ┌───────────┐
 │  OUTPUT   │ Strip sensitive values, serialize objects/dicts to pure JSON
 └───────────┘


NOTE FOR BEGINNERS ON SCHEMAS (Pydantic):

Pydantic schemas act as data contracts. They define what data comes IN (PostCreate)
and what data goes OUT (PostResponse). They handle:
  1. Data Validation (validating types like checking if an ID is an integer)
  2. Serialization (converting database objects/dictionaries into clean JSON)
  3. Auto-Documentation (automatically building data shapes for Swagger UI at /docs)
--------------------------------------------------------
NOTE FOR BEGINNERS ON PYDANTIC TOOLS:
1. BaseModel: The core blueprint class. All data schemas inherit from this.
2. Field: Allows you to inject validation constraints (like text length boundaries)
   and custom metadata directly onto schema attributes.
3. ConfigDict: The modern Pydantic v2 setup manager used to change how models behave.
--------------------------------------------------------

"""


class UserBase(BaseModel):
    username: str = Field(min_length=1, max_length=50)
    email: EmailStr = Field(max_length=120)


class UserCreate(UserBase):
    pass


class UserResponse(UserBase):
    model_config = ConfigDict(from_attributes=True)
    id: int
    image_file: str|None
    image_path: str
    # image_path define in model it is not database col from_attributes let read that attribute 

class UserUpdate(BaseModel):
    username: str | None= Field(default=None,min_length=1, max_length=50)
    email: EmailStr | None = Field(default=None, max_length=120)
    image_file: str | None= Field(default=None,min_length=1, max_length=500)

class PostBase(BaseModel):
    """
    The Shared Base Schema.

    Contains fields common to both creating a post and returning a post.
    By enforcing validation constraints here, we don't repeat code.
    """
    title: str = Field(min_length=1, max_length=100, description="The headline of the post")
    content: str = Field(min_length=1, description="The main body text of the post")
    author: str = Field(min_length=1, max_length=50, description="The author's display name")


class PostCreate(PostBase):
    """
    Data Contract for Inbound Requests (Data coming IN).

    Inherits all fields from PostBase. When a user creates a post, they only need
    to supply a title, content, and author. The application handles the ID and dates.
    """
    pass
    user_id:int #TEMP
    
class PostUpdate(BaseModel):
    title: str | None = Field(default=None, min_length=1, max_length=100, description="The headline of the post")
    content: str | None = Field(default=None, min_length=1, description="The main body text of the post")
    user_id: int | None = Field(default=None, description="The ID of the user who owns this post")


    
class PostResponse(PostBase):
        """
        Data Contract for Outbound Responses (Data going OUT).
    
        Includes all core fields from PostBase, plus extra fields generated by the
        backend (like the database ID and the exact timestamp when it was stored).
        """
        # Enables Pydantic to read data structures from Object-Relational Mappers (ORMs)
        # like SQLAlchemy. This allows Pydantic to extract fields using dot notation
        # (e.g., post.title) instead of just dictionary lookups (e.g., post["title"]).
        model_config = ConfigDict(from_attributes=True)
    
        id: int #scope to classs not give any linter worning
        user_id:int
        date_posted: datetime
        author: UserResponse #get nested user id, email, and other in json response


    # from_attributes: it can read data from the attributes not just dictnory help full when add the database
    # right now acess data with post["title"]
    #pydentic alresay how to read data from dic by doing this it will allow how to read  object using dot notations data from database
    #when add database data will be going to acess through post.title
    #field that we want in respone but not provied by client
